# This is a basic workflow to help you get started with Actions

name: snyk integration

# Controls when the workflow will run
on:
  push:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: snyk/actions/maven@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --sarif-file-output-snyk-sarif.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: upload sarif file
        uses: github/codeql action/upload sarif@v1
        with: 
          sarif_file: snyk.sarif.json
        with:
          args: --severity-threshold=high
